//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBAlert.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.FBAlerterSoap")]
    public interface FBAlerterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloFB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloFB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloFB", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloFBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FBAlert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FBAlert(string System, string MessageCata, string AlertMessage, string Priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FBAlert", ReplyAction="*")]
        System.Threading.Tasks.Task<string> FBAlertAsync(string System, string MessageCata, string AlertMessage, string Priority);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FBAlerterSoapChannel : FBAlert.ServiceReference2.FBAlerterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FBAlerterSoapClient : System.ServiceModel.ClientBase<FBAlert.ServiceReference2.FBAlerterSoap>, FBAlert.ServiceReference2.FBAlerterSoap {
        
        public FBAlerterSoapClient() {
        }
        
        public FBAlerterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FBAlerterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FBAlerterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FBAlerterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloFB() {
            return base.Channel.HelloFB();
        }
        
        public System.Threading.Tasks.Task<string> HelloFBAsync() {
            return base.Channel.HelloFBAsync();
        }
        
        public string FBAlert(string System, string MessageCata, string AlertMessage, string Priority) {
            return base.Channel.FBAlert(System, MessageCata, AlertMessage, Priority);
        }
        
        public System.Threading.Tasks.Task<string> FBAlertAsync(string System, string MessageCata, string AlertMessage, string Priority) {
            return base.Channel.FBAlertAsync(System, MessageCata, AlertMessage, Priority);
        }
    }
}
